---
name: "Extension upload"
on:
  push:
    tags:
      - v*
jobs:
  UploadExtension:
    name: Extension upload & publish
    runs-on: ubuntu-latest
    env:
      APP_ID: bkbejdaeamaehgpodkjdbkhkofpijagn
    steps:
      - uses: actions/checkout@v4
      - name: install node v19
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci
      - run: npm run build
      - run: npm run bundle
      - uses: actions/upload-artifact@v3
        with:
          name: extension
          path: ./extension.zip
      - name: Upload extension
        uses: cardinalby/webext-buildtools-chrome-webstore-action@v1
        with:
          zipFilePath: './extension.zip'
          extensionId: ${{ env.APP_ID }}
          apiClientId: ${{ secrets.CLIENT_ID }}
          apiClientSecret: ${{ secrets.CLIENT_SECRET }}
          apiRefreshToken: ${{ secrets.REFRESH_TOKEN }}
      - name: Publish extension
        uses: cardinalby/webext-buildtools-chrome-webstore-publish-action@v1
        with:
          extensionId: ${{ env.APP_ID }}
          apiClientId: ${{ secrets.CLIENT_ID }}
          apiClientSecret: ${{ secrets.CLIENT_SECRET }}
          apiRefreshToken: ${{ secrets.REFRESH_TOKEN }}
      - name: Deploy to Edge Addons
        uses: wdzeng/edge-addon@v1.0.3
        with:
          product-id: ${{ secrets.EDGE_PRODUCT_ID }}
          zip-path: './extension.zip'
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
